export const sampleEvents = [
  {
    id: '1',
    title: '색칠공부 콘테스트',
    place: '동대문구',
    target: '5세 이상',
    org: '마포아트센터',
    date: '2024.05.31 - 06.08',
    image: require('@/assets/images/icon.png'),
  },
  {
    id: '2',
    title: '행복한 하루 축제',
    place: '동대문구',
    target: '5세 이상',
    org: '마포아트센터',
    date: '2024.05.04 - 05.05',
    image: require('@/assets/images/icon.png'),
  },
  {
    id: '3',
    title: '고전 게임 박람회',
    place: '동대문구',
    target: '5세 이상',
    org: '마포아트센터',
    date: '2024.05.06',
    image: require('@/assets/images/icon.png'),
  },
  {
    id: '4',
    title: '색칠공부 콘테스트',
    place: '동대문구',
    target: '5세 이상',
    org: '마포아트센터',
    date: '2024.05.31 - 06.08',
    image: require('@/assets/images/icon.png'),
  },
  {
    id: '5',
    title: '행복한 하루 축제',
    place: '동대문구',
    target: '5세 이상',
    org: '마포아트센터',
    date: '2024.05.04 - 05.05',
    image: require('@/assets/images/icon.png'),
  },
  {
    id: '6',
    title: '고전 게임 박람회',
    place: '동대문구',
    target: '5세 이상',
    org: '마포아트센터',
    date: '2024.05.06',
    image: require('@/assets/images/icon.png'),
  },
];
export const samplecategories = [
  '전시·미술',
  '공연',
  '교육체험',
  '축제',
  '영화',
  '기타',
];
